packages:
  - 'api'
  - 'features/**'
  - 'packages/**'
  - 'shared/**'
  - 'web'
  - 'web-e2e'

allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  esbuild: true
  less: false
  lmdb: false
  msgpackr-extract: false
  nx: true
  sharp: true
  unrs-resolver: true
